name: photographic_viewer
description: Photographic viewer for Desktop(Mac or Linux)

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.1
  exif: ^3.1.2
  share_plus: ^4.0.10
  path: ^1.8.1
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
