name: build macos

on:
  push:
    paths-ignore:
      - 'linux/**'
      - 'windows/**'
  pull_request:
    paths-ignore:
      - 'linux/**'
      - 'windows/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{vars.FLUTTER_SDK_VERSION}}
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
    - run: flutter config --enable-macos-desktop
    - run: flutter build macos
