name: Check source code
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows'
  pull_request:
    paths-ignore:
      - '.github/workflows'


jobs:
  test:
    name: Check source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.3.1'
            channel: 'stable'
            cache: true
            cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - name: Install
        run: flutter pub get
      - name: Linter
        run: flutter analyze
