  name: 'Release macos zip'
  on: [release]
  jobs:
    release:
      runs-on: macos-latest
      env:
        APP_NAME: PhotographicViewer
        MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
      steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter build macos
      - name: zip
        run: zip -r PhotographicViewer.mac.zip PhotographicViewer.app
        working-directory: ./build/macos/Build/Products/Release
      - name: install create_dmg
      - run: |
          brew update
          brew install create_dmg
      - name create_dmg
      - run: create-dmg \
  --volname PhotographicViewer \
  --window-pos 200 120 \
  --window-size 800 529 \
  --icon-size 130 \
  --text-size 14 \
  --icon PhotographicViewer 260 250 \
  --hide-extension PhotograpicViewer \
  --app-drop-link 540 250 \
  --hdiutil-quiet \
  PhotographicViewer.dmg \
  PhotographicViewer.app
        working-directory: ./build/macos/Build/Products/Release
      - uses: softprops/action-gh-release@v1
        with:
          files: ./build/macos/Build/Products/Release/PhotographicViewer.mac.zip
