name: 'Release macos zip'
on: [release]
jobs:
  release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
    - run: flutter build macos
    - name: zip
      run: zip -r PhotographicViewer.mac.zip PhotographicViewer.app
      working-directory: ./build/macos/Build/Products/Release
    - uses: softprops/action-gh-release@v1
      with:
        files: ./build/macos/Build/Products/Release/PhotographicViewer.mac.zip
