  name: 'Release macos archives'
  on: [release]
  jobs:
    release:
      runs-on: macos-latest
      env:
        APP_NAME: PhotographicViewer
        MACOS_APP_RELEASE_PATH: ./build/macos/Build/Products/Release
      steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter build macos
      - name: zip
        run: zip -r ${{ env.APP_NAME }}.mac.zip ${{ env.APP_NAME }}.app
        working-directory: ${{ env.MACOS_APP_RELEASE_PATH }}
      - name: Install create-dmg
        run: |
          brew update
          brew install create-dmg
      - name: Create DMG Installer
        run: |
          create-dmg \
            --volname ${APP_NAME} \
            --window-pos 200 120 \
            --window-size 800 529 \
            --icon-size 130 \
            --text-size 14 \
            --icon ${APP_NAME} 260 250 \
            --hide-extension ${APP_NAME} \
            --app-drop-link 540 250 \
            --hdiutil-quiet \
            ${APP_NAME}.dmg \
            ${APP_NAME}.app
        working-directory: ${{ env.MACOS_APP_RELEASE_PATH }}
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.APP_NAME }}.mac.zip
            ${{ env.APP_NAME }}.dmg
        working-directory: ${{ env.MACOS_APP_RELEASE_PATH }}

